import type { Metadata } from "next";
import { VT323 } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import SmoothScroll from "@/components/SmoothScroll";

const vT323 = VT323({
  weight: ["400"],
  subsets: ["latin"]
});

const helveticaNeueHeavy = localFont({
  src: "/fonts/HelveticaNeueHeavy.otf"
});

export const metadata: Metadata = {
  title: "mateja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helveticaNeueHeavy.className} antialiased`}
      >
        <SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
